version: '3'

services:
  node-api:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=server
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=server