version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: be-the-hero-api
    restart: always
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run start:dev"
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - postgres
    depends_on:
      - postgres
          
volumes:
  pgdata:
